import type { WorkoutDay, EllipticalSession } from "./types";

/* ─── Reusable Elliptical Sessions ─── */

export const HIIT_SESSION: EllipticalSession = {
  id: "elliptical-hiit",
  name: "Elliptical HIIT",
  totalMinutes: 27,
  estimatedCalories: 280,
  intervals: [
    { id: "e1", label: "Easy Warm-up", resistance: 3, durationSeconds: 120, pace: "easy", note: "Settle into rhythm, breathe through nose" },
    { id: "e2", label: "Warm-up Build", resistance: 4, durationSeconds: 120, pace: "easy", note: "Slightly increase cadence" },
    { id: "e3", label: "Warm-up Push", resistance: 5, durationSeconds: 60,  pace: "moderate", note: "Getting the heart rate up" },
    { id: "e4", label: "Sprint Round 1", resistance: 10, durationSeconds: 60, pace: "sprint", note: "Push hard — drive with legs AND arms" },
    { id: "e5", label: "Recovery 1",    resistance: 4,  durationSeconds: 120, pace: "recovery", note: "Active recovery, keep moving" },
    { id: "e6", label: "Sprint Round 2", resistance: 10, durationSeconds: 60, pace: "sprint" },
    { id: "e7", label: "Recovery 2",    resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e8", label: "Sprint Round 3", resistance: 11, durationSeconds: 60, pace: "sprint", note: "Increase resistance this round" },
    { id: "e9", label: "Recovery 3",    resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e10", label: "Sprint Round 4", resistance: 11, durationSeconds: 60, pace: "sprint" },
    { id: "e11", label: "Recovery 4",   resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e12", label: "Sprint Round 5", resistance: 11, durationSeconds: 60, pace: "sprint", note: "Dig deep — last hard rounds!" },
    { id: "e13", label: "Recovery 5",   resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e14", label: "Sprint Round 6", resistance: 10, durationSeconds: 60, pace: "sprint" },
    { id: "e15", label: "Recovery 6",   resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e16", label: "Cool Down",    resistance: 2,  durationSeconds: 300, pace: "cooldown", note: "Gradual slow-down, deep breathing" },
  ],
};

export const FAT_BURN_SESSION: EllipticalSession = {
  id: "elliptical-fat-burn",
  name: "Fat Burn Steady State",
  totalMinutes: 35,
  estimatedCalories: 320,
  intervals: [
    { id: "f1", label: "Warm-up",    resistance: 3, durationSeconds: 300, pace: "easy",     note: "Build into zone 2 — conversational pace" },
    { id: "f2", label: "Fat Burn Zone", resistance: 5, durationSeconds: 1500, pace: "moderate", note: "You can talk in sentences but can't sing. Resistance 5–6" },
    { id: "f3", label: "Cool Down",  resistance: 2, durationSeconds: 300, pace: "cooldown", note: "Let heart rate come down naturally" },
  ],
};

/* ─── 6-Week Program ─── */

export const WORKOUT_PROGRAM: WorkoutDay[] = [
  /* ──────────── DAY 1 – Cardio HIIT + Abs ──────────── */
  {
    dayNumber: 1,
    name: "Cardio HIIT + Abs",
    focus: "Cardiovascular conditioning & core",
    durationMinutes: 45,
    intensity: 4,
    muscleGroups: ["Core", "Full body cardio"],
    tags: ["hiit", "cardio", "abs", "fat-burn"],
    warmup: [
      { id: "w1-1", activity: "Cat–Cow", reps: 8, note: "Slow and controlled — mobilize the spine" },
      { id: "w1-2", activity: "Slow Bodyweight Squats", reps: 10, note: "Feet shoulder-width apart, go to depth" },
      { id: "w1-3", activity: "Arm Circles", reps: 10, note: "10 forward, 10 backward — warm shoulder joint" },
    ],
    exercises: [
      {
        id: "d1-plank",
        name: "Plank",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis", "Rectus abdominis"],
        musclesSecondary: ["Glutes", "Shoulders"],
        description: "Hold a straight-body position supported on forearms and toes. Think of creating a stiff plank from head to heel.",
        dos: ["Keep hips level — not sagging or piked", "Drive elbows into floor", "Breathe steadily throughout", "Squeeze glutes"],
        donts: ["Let hips drop or rise", "Hold your breath", "Crane your neck forward"],
        breathingCue: "Inhale through nose, slow exhale through mouth — brace on exhale",
        safetyNotes: "If lower back hurts, drop to knees and build up",
        phase: "core",
        order: 1,
        sets: [
          { id: "d1-plank-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 45, restSeconds: 30 },
          { id: "d1-plank-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 50, restSeconds: 30 },
          { id: "d1-plank-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 30 },
        ],
      },
      {
        id: "d1-llr",
        name: "Lying Leg Raises",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Lower rectus abdominis", "Hip flexors"],
        musclesSecondary: ["Transverse abdominis"],
        description: "Lie flat on your back, legs together. Raise legs to 90° keeping them straight, then lower slowly without touching floor.",
        dos: ["Press lower back into the mat", "Control the descent — 3 seconds down", "Exhale as legs rise"],
        donts: ["Let lower back arch off the floor", "Swing legs with momentum", "Let feet touch the ground between reps"],
        breathingCue: "Exhale as legs go up, inhale as they come down",
        phase: "core",
        order: 2,
        sets: [
          { id: "d1-llr-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d1-llr-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d1-llr-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30 },
        ],
      },
      {
        id: "d1-bicycle",
        name: "Bicycle Crunch",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Obliques", "Rectus abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Lie on back, hands behind head. Alternate bringing elbow to opposite knee in a cycling motion. Slow and deliberate.",
        dos: ["Rotate torso — not just elbows", "Keep lower back pressed down", "Full extension of opposite leg each rep"],
        donts: ["Pull on your neck", "Rush the movement", "Let shoulders hunch"],
        breathingCue: "Exhale forcefully on each rotation",
        phase: "core",
        order: 3,
        sets: [
          { id: "d1-bicycle-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-bicycle-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-bicycle-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
      {
        id: "d1-heel",
        name: "Heel Touches",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Obliques"],
        musclesSecondary: ["Rectus abdominis"],
        description: "Lie on back, knees bent, feet flat. Crunch side-to-side to touch each heel alternately.",
        dos: ["Keep shoulder blades slightly off floor throughout", "Look at the ceiling, not your feet", "Touch each heel fully"],
        donts: ["Relax back to the floor between reps", "Rush — control the movement"],
        breathingCue: "Exhale on each touch",
        phase: "core",
        order: 4,
        sets: [
          { id: "d1-heel-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-heel-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-heel-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
    ],
    elliptical: HIIT_SESSION,
    cooldown: [
      { id: "c1-1", activity: "Walking on the spot", durationSeconds: 120, note: "Let heart rate come down" },
      { id: "c1-2", activity: "Standing forward fold", durationSeconds: 30 },
      { id: "c1-3", activity: "Standing hip flexor stretch (each side)", durationSeconds: 30 },
      { id: "c1-4", activity: "Deep breathing", reps: 5, note: "4-count in, 6-count out" },
    ],
  },

  /* ──────────── DAY 2 – Biceps Focus + Upper Body ──────────── */
  {
    dayNumber: 2,
    name: "Biceps Focus + Upper Body",
    focus: "Biceps hypertrophy, triceps, shoulders",
    durationMinutes: 50,
    intensity: 4,
    muscleGroups: ["Biceps", "Triceps", "Shoulders"],
    tags: ["biceps", "upper-body", "hypertrophy"],
    warmup: [
      { id: "w2-1", activity: "Light Elliptical", durationSeconds: 150, note: "Resistance 3 — just elevate heart rate" },
      { id: "w2-2", activity: "Arm Circles", reps: 20, note: "20 forward + 20 backward" },
      { id: "w2-3", activity: "Shoulder Rolls", reps: 15 },
      { id: "w2-4", activity: "Wrist Circles", reps: 20, note: "20 each direction" },
      { id: "w2-5", activity: "Elbow Flex–Extend", reps: 15, note: "No weight — prime the elbow joint" },
      { id: "w2-6", activity: "Light DB Curl (ramp-up set 1)", reps: 15, note: "Rod only — slow and controlled" },
      { id: "w2-7", activity: "Ramp-Up Curl Set 2 (50%)", reps: 12, note: "~1.5 kg per dumbbell — easy, controlled. Rest 30 sec" },
      { id: "w2-8", activity: "Ramp-Up Curl Set 3 (70%)", reps: 8,  note: "~2 kg per dumbbell — smooth, slightly challenging. Rest 45 sec" },
    ],
    exercises: [
      {
        id: "d2-standing-curl",
        name: "Standing Dumbbell Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Biceps brachii (short + long head)"],
        musclesSecondary: ["Brachialis", "Brachioradialis", "Forearm flexors"],
        description: "Stand tall with dumbbells at sides. Curl both dumbbells simultaneously while keeping elbows pinned to your ribcage. Squeeze hard at the top, then lower in 3 seconds.",
        dos: ["Elbows glued to sides throughout", "Full range — complete stretch at bottom", "2 seconds up, 3 seconds down (2-0-3 tempo)", "Supinate wrists at the top (rotate pinky up)"],
        donts: ["Swing body or use momentum", "Allow elbows to drift forward", "Lock wrists awkwardly", "Cut the range of motion short"],
        breathingCue: "Exhale as you curl up, inhale on the way down",
        safetyNotes: "Stop if you feel sharp elbow pain — reduce weight",
        phase: "main",
        order: 1,
        sets: [
          { id: "d2-sc-s1", setNumber: 1, targetWeight: 4, targetReps: 10, restSeconds: 75, tempo: "2-0-3-0", notes: "2+2 kg plates. Focus on form" },
          { id: "d2-sc-s2", setNumber: 2, targetWeight: 4, targetReps: 9,  restSeconds: 75, tempo: "2-0-3-0" },
          { id: "d2-sc-s3", setNumber: 3, targetWeight: 4, targetReps: 8,  restSeconds: 90, tempo: "2-0-3-0", notes: "Last set — push to near failure" },
          { id: "d2-sc-s4", setNumber: 4, targetWeight: 4, targetReps: 8,  restSeconds: 90, tempo: "2-0-3-0" },
        ],
      },
      {
        id: "d2-hammer-curl",
        name: "Hammer Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Brachialis", "Brachioradialis"],
        musclesSecondary: ["Biceps brachii"],
        description: "Neutral grip (thumbs up) curl. Builds the brachialis underneath the bicep, making it look thicker and pushes the peak higher.",
        dos: ["Neutral grip throughout — don't rotate", "Elbows stay at sides", "Full extension at the bottom", "Controlled 3-second descent"],
        donts: ["Supinate — keep thumbs up the whole time", "Use heavy weight at the expense of form", "Rush the eccentric"],
        breathingCue: "Exhale curling up, inhale coming down",
        phase: "main",
        order: 2,
        sets: [
          { id: "d2-hc-s1", setNumber: 1, targetWeight: 3, targetReps: 12, restSeconds: 60, notes: "1.5+1.5 kg" },
          { id: "d2-hc-s2", setNumber: 2, targetWeight: 3, targetReps: 10, restSeconds: 60 },
          { id: "d2-hc-s3", setNumber: 3, targetWeight: 3, targetReps: 10, restSeconds: 60 },
        ],
      },
      {
        id: "d2-incline-curl",
        name: "Incline / Seated Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "intermediate",
        musclesPrimary: ["Biceps brachii long head"],
        musclesSecondary: ["Brachialis"],
        description: "Sit on the edge of a chair/couch leaning slightly back. Arms hang behind the body plane — this gives maximum stretch to the long head of the bicep for superior growth.",
        dos: ["Let arms hang freely behind hips", "Curl slowly from full stretch", "Squeeze at top for 1 second", "Keep shoulders back"],
        donts: ["Swing forward to help the lift", "Use too heavy weight — this is a stretch movement", "Round shoulders forward"],
        breathingCue: "Long exhale as you curl, slow inhale on descent",
        phase: "main",
        order: 3,
        sets: [
          { id: "d2-ic-s1", setNumber: 1, targetWeight: 3, targetReps: 12, restSeconds: 60, notes: "1.5+1.5 kg — lighter than curls" },
          { id: "d2-ic-s2", setNumber: 2, targetWeight: 3, targetReps: 10, restSeconds: 60 },
          { id: "d2-ic-s3", setNumber: 3, targetWeight: 3, targetReps: 10, restSeconds: 60 },
        ],
      },
      {
        id: "d2-tricep-ext",
        name: "Overhead DB Triceps Extension",
        category: "triceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Triceps brachii (long head)"],
        musclesSecondary: ["Anconeus"],
        description: "Hold one dumbbell overhead with both hands. Lower it behind your head by bending elbows, keeping upper arms vertical. Extend back up.",
        dos: ["Keep upper arms vertical and still", "Full range of motion — get a deep stretch at the bottom", "Elbows close together", "Very light weight — this is an isolation move"],
        donts: ["Flare elbows wide", "Use heavy weight", "Let upper arms drift forward"],
        breathingCue: "Inhale going down (stretch), exhale driving up",
        phase: "main",
        order: 4,
        sets: [
          { id: "d2-te-s1", setNumber: 1, targetWeight: 3, targetReps: 15, restSeconds: 45, notes: "Both hands on one dumbbell" },
          { id: "d2-te-s2", setNumber: 2, targetWeight: 3, targetReps: 12, restSeconds: 45 },
          { id: "d2-te-s3", setNumber: 3, targetWeight: 3, targetReps: 12, restSeconds: 45 },
        ],
      },
      {
        id: "d2-lateral-raise",
        name: "Lateral Raise",
        category: "shoulders",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Lateral deltoid"],
        musclesSecondary: ["Anterior deltoid", "Supraspinatus"],
        description: "Stand with light dumbbells at sides. Raise arms out to the sides to shoulder height with a slight bend in the elbow. 1-second pause at top.",
        dos: ["Keep very light weight (1.25 kg per side)", "Raise to shoulder height only — not above", "Slight forward lean improves lateral delt engagement", "1-second squeeze at the top"],
        donts: ["Use momentum or shrug", "Go above shoulder height", "Lock elbows straight"],
        breathingCue: "Exhale as arms rise, inhale on way down",
        phase: "main",
        order: 5,
        sets: [
          { id: "d2-lr-s1", setNumber: 1, targetWeight: 2.5, targetReps: 15, restSeconds: 45, notes: "1.25+1.25 kg — extremely light, focus on squeeze" },
          { id: "d2-lr-s2", setNumber: 2, targetWeight: 2.5, targetReps: 12, restSeconds: 45 },
          { id: "d2-lr-s3", setNumber: 3, targetWeight: 2.5, targetReps: 12, restSeconds: 45 },
        ],
      },
    ],
    cooldown: [
      { id: "c2-1", activity: "Bicep wall stretch (each arm)", durationSeconds: 30 },
      { id: "c2-2", activity: "Overhead triceps stretch (each arm)", durationSeconds: 30 },
      { id: "c2-3", activity: "Shoulder cross-body stretch (each arm)", durationSeconds: 30 },
      { id: "c2-4", activity: "Wrist flexor & extensor stretch", durationSeconds: 30 },
    ],
  },

  /* ──────────── DAY 3 – Fat Burn Elliptical + Core ──────────── */
  {
    dayNumber: 3,
    name: "Fat Burn Cardio + Core",
    focus: "Aerobic fat burn & core strengthening",
    durationMinutes: 50,
    intensity: 3,
    muscleGroups: ["Core", "Cardiovascular system"],
    tags: ["cardio", "fat-burn", "core", "steady-state"],
    warmup: [
      { id: "w3-1", activity: "Nasal breathing walk in place", durationSeconds: 90 },
      { id: "w3-2", activity: "Hip circles", reps: 10, note: "10 each direction" },
      { id: "w3-3", activity: "Arm circles", reps: 20, note: "20 forward + 20 backward" },
      { id: "w3-4", activity: "Shoulder rolls", reps: 15 },
    ],
    exercises: [
      {
        id: "d3-side-plank",
        name: "Side Plank",
        category: "core",
        equipment: "bodyweight",
        difficulty: "intermediate",
        musclesPrimary: ["Obliques (internal + external)", "Quadratus lumborum"],
        musclesSecondary: ["Glutes", "Shoulder stabilisers"],
        description: "Lie on side, prop up on forearm with elbow under shoulder. Lift hips to create a straight line from head to feet. Hold.",
        dos: ["Stack feet or stagger for easier balance", "Keep hips stacked — don't rotate forward", "Push forearm into floor actively", "Look forward"],
        donts: ["Let hips sag", "Rotate your top hip back", "Forget to do both sides"],
        breathingCue: "Steady breathing — in through nose, out through mouth",
        phase: "core",
        order: 1,
        sets: [
          { id: "d3-sp-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 35, notes: "Both sides = 1 set" },
          { id: "d3-sp-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 35, restSeconds: 35 },
          { id: "d3-sp-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 40, restSeconds: 35 },
        ],
      },
      {
        id: "d3-dead-bug",
        name: "Dead Bug",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis", "Rectus abdominis"],
        musclesSecondary: ["Hip flexors", "Shoulder stabilisers"],
        description: "Lie on back, arms straight up over shoulders, knees bent at 90° over hips. Slowly lower opposite arm + leg toward floor while pressing lower back down, then return.",
        dos: ["Press lower back firmly into the mat throughout", "Move arm and leg simultaneously", "Exhale FULLY on each rep", "Move slowly — 3 seconds each way"],
        donts: ["Let lower back arch off the floor", "Rush the movement", "Hold your breath"],
        breathingCue: "Exhale as limbs extend, inhale as they return",
        phase: "core",
        order: 2,
        sets: [
          { id: "d3-db-s1", setNumber: 1, targetWeight: null, targetReps: 10, restSeconds: 30, notes: "10 per side = 1 set" },
          { id: "d3-db-s2", setNumber: 2, targetWeight: null, targetReps: 10, restSeconds: 30 },
          { id: "d3-db-s3", setNumber: 3, targetWeight: null, targetReps: 10, restSeconds: 30 },
        ],
      },
      {
        id: "d3-reverse-crunch",
        name: "Reverse Crunch",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Lower rectus abdominis"],
        musclesSecondary: ["Transverse abdominis", "Hip flexors"],
        description: "Lie on back, knees bent at 90°. Curl the pelvis upward — bringing knees toward chest by contracting the lower abs, not swinging. Lower with control.",
        dos: ["Focus on curling the pelvis — small controlled movement", "Exhale hard at the top", "Control the eccentric (3 second lower)", "Hands flat by sides for stability"],
        donts: ["Swing legs — that's hip flexors, not abs", "Let lower back slam down", "Use momentum"],
        breathingCue: "Exhale forcefully as pelvis curls up",
        phase: "core",
        order: 3,
        sets: [
          { id: "d3-rc-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d3-rc-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d3-rc-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30 },
        ],
      },
    ],
    elliptical: FAT_BURN_SESSION,
    cooldown: [
      { id: "c3-1", activity: "Thread-the-needle stretch (each side)", durationSeconds: 30 },
      { id: "c3-2", activity: "Child's pose", durationSeconds: 45 },
      { id: "c3-3", activity: "Hip flexor stretch (each side)", durationSeconds: 30 },
      { id: "c3-4", activity: "Savasana — deep rest", durationSeconds: 180, note: "Eyes closed, full-body relaxation" },
    ],
  },

  /* ──────────── DAY 4 – Biceps Volume + Chest Push ──────────── */
  {
    dayNumber: 4,
    name: "Biceps Volume + Chest",
    focus: "Biceps volume accumulation & chest/triceps",
    durationMinutes: 50,
    intensity: 4,
    muscleGroups: ["Biceps", "Chest", "Triceps"],
    tags: ["biceps", "chest", "push", "volume"],
    warmup: [
      { id: "w4-1", activity: "Light Elliptical / Brisk Walk", durationSeconds: 150, note: "Resistance 3–4 — just raise body temperature" },
      { id: "w4-2", activity: "Arm Circles (small → big)", reps: 20, note: "20 forward + 20 backward" },
      { id: "w4-3", activity: "Shoulder Rolls", reps: 15 },
      { id: "w4-4", activity: "Wrist Circles", reps: 20, note: "20 each direction" },
      { id: "w4-5", activity: "Elbow Flex–Extend", reps: 15, note: "No weight" },
      { id: "w4-6", activity: "Light DB Curl (rod only)", reps: 15 },
      { id: "w4-7", activity: "Ramp-Up — Alternating DB Curl 50%", reps: 12 },
      { id: "w4-8", activity: "Ramp-Up — Alternating DB Curl 70%", reps: 8 },
    ],
    exercises: [
      {
        id: "d4-alt-curl",
        name: "Alternating Dumbbell Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Biceps brachii"],
        musclesSecondary: ["Brachialis", "Forearm flexors"],
        description: "Curl one arm at a time while the other stays lowered. Allows slightly more focus on each arm and greater volume accumulation.",
        dos: ["Fully lower one arm before starting the other", "Supinate on the way up", "Elbows stay at sides", "Same tempo — 2 up, 3 down"],
        donts: ["Rush — treat each arm independently", "Lean to help one side", "Forget the eccentric on each rep"],
        breathingCue: "Exhale with each curl, inhale on descent",
        phase: "main",
        order: 1,
        sets: [
          { id: "d4-ac-s1", setNumber: 1, targetWeight: 4, targetReps: 12, restSeconds: 75, tempo: "2-0-3-0" },
          { id: "d4-ac-s2", setNumber: 2, targetWeight: 4, targetReps: 12, restSeconds: 75 },
          { id: "d4-ac-s3", setNumber: 3, targetWeight: 4, targetReps: 10, restSeconds: 75 },
          { id: "d4-ac-s4", setNumber: 4, targetWeight: 4, targetReps: 10, restSeconds: 90 },
        ],
      },
      {
        id: "d4-concentration-curl",
        name: "Concentration Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Biceps brachii (peak)"],
        musclesSecondary: ["Brachialis"],
        description: "Sit with legs apart, rest elbow on inner thigh. Curl with full focus on that arm. This isolates the bicep peak.",
        dos: ["Rest elbow on INNER thigh — not the top of thigh", "Full range — complete stretch at bottom", "Rotate wrist outward (pinky up) at the top", "Go slow on the way down"],
        donts: ["Rest elbow mid-thigh (too unstable)", "Swing upper arm", "Use too much weight"],
        breathingCue: "Exhale curling, inhale descending",
        phase: "main",
        order: 2,
        sets: [
          { id: "d4-cc-s1", setNumber: 1, targetWeight: 3.5, targetReps: 12, restSeconds: 60, notes: "Each arm. 1.5+0.5 plates (or 2kg dumbbell)" },
          { id: "d4-cc-s2", setNumber: 2, targetWeight: 3.5, targetReps: 12, restSeconds: 60 },
          { id: "d4-cc-s3", setNumber: 3, targetWeight: 3.5, targetReps: 10, restSeconds: 60 },
        ],
      },
      {
        id: "d4-pushup",
        name: "Push-ups",
        category: "chest",
        equipment: "pushup_bracket",
        difficulty: "beginner",
        musclesPrimary: ["Pectoralis major", "Anterior deltoid"],
        musclesSecondary: ["Triceps brachii", "Serratus anterior"],
        description: "Use push-up brackets for deeper range of motion. Hands shoulder-width apart, lower chest to bracket level (lower than floor!), press back up.",
        dos: ["Use brackets to get extra depth (incredible chest stretch)", "Keep body rigid — squeeze core and glutes", "Lower in 2 seconds, press in 1 second", "Elbows at 45° angle to torso"],
        donts: ["Sag hips or pike them up", "Let elbows flare to 90°", "Rush the descent"],
        breathingCue: "Inhale going down, exhale pressing up",
        phase: "main",
        order: 3,
        sets: [
          { id: "d4-pu-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 60 },
          { id: "d4-pu-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 60 },
          { id: "d4-pu-s3", setNumber: 3, targetWeight: null, targetReps: 12, restSeconds: 60 },
          { id: "d4-pu-s4", setNumber: 4, targetWeight: null, targetReps: 12, restSeconds: 60 },
        ],
      },
      {
        id: "d4-diamond-pushup",
        name: "Diamond Push-ups",
        category: "triceps",
        equipment: "pushup_bracket",
        difficulty: "intermediate",
        musclesPrimary: ["Triceps brachii (all 3 heads)"],
        musclesSecondary: ["Inner chest", "Anterior deltoid"],
        description: "Form a diamond shape with index fingers and thumbs. Lower chest to hands, press back up. Intense triceps isolation.",
        dos: ["Keep diamond shape tight at centre of chest", "Full ROM — chest touches hands at bottom", "Elbows stay close to body", "Take extra rest — these are hard"],
        donts: ["Flare elbows out", "Partial reps — go all the way down", "Rush if fatigued"],
        breathingCue: "Inhale down, exhale up",
        phase: "main",
        order: 4,
        sets: [
          { id: "d4-dp-s1", setNumber: 1, targetWeight: null, targetReps: 10, restSeconds: 75 },
          { id: "d4-dp-s2", setNumber: 2, targetWeight: null, targetReps: 8,  restSeconds: 75 },
          { id: "d4-dp-s3", setNumber: 3, targetWeight: null, targetReps: 8,  restSeconds: 75 },
        ],
      },
    ],
    cooldown: [
      { id: "c4-1", activity: "Chest doorway stretch", durationSeconds: 30 },
      { id: "c4-2", activity: "Bicep wall stretch (each arm)", durationSeconds: 30 },
      { id: "c4-3", activity: "Triceps overhead stretch (each arm)", durationSeconds: 30 },
      { id: "c4-4", activity: "Cat–Cow", reps: 8 },
    ],
  },

  /* ──────────── DAY 5 – HIIT + Abs ──────────── */
  {
    dayNumber: 5,
    name: "HIIT Cardio + Abs",
    focus: "High-intensity interval training & core burn",
    durationMinutes: 45,
    intensity: 5,
    muscleGroups: ["Core", "Full body cardio"],
    tags: ["hiit", "cardio", "abs", "high-intensity"],
    warmup: [
      { id: "w5-1", activity: "Easy Elliptical", durationSeconds: 120, note: "Resistance 3 — just loosen up" },
      { id: "w5-2", activity: "Marching Knee Raises", durationSeconds: 60 },
      { id: "w5-3", activity: "Arm circles", reps: 20 },
      { id: "w5-4", activity: "Ankle rotations", reps: 10, note: "10 each leg" },
    ],
    exercises: [
      {
        id: "d5-plank",
        name: "Plank",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis", "Rectus abdominis"],
        musclesSecondary: ["Glutes", "Shoulders"],
        description: "Hold a straight-body position on forearms and toes. Core braced like you're about to take a punch.",
        dos: ["Neutral spine", "Drive elbows into floor", "Squeeze glutes hard"],
        donts: ["Let hips sag or rise", "Hold breath"],
        breathingCue: "Slow steady breaths — don't hold",
        phase: "core", order: 1,
        sets: [
          { id: "d5-pl-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 50, restSeconds: 30 },
          { id: "d5-pl-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 55, restSeconds: 30 },
          { id: "d5-pl-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 30 },
        ],
      },
      {
        id: "d5-llr",
        name: "Lying Leg Raises",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Lower rectus abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Lie flat, raise legs to 90°, lower in 3 seconds without touching the floor.",
        dos: ["Lower back pressed down", "3-second descent", "No floor touch between reps"],
        donts: ["Arch lower back", "Use momentum"],
        breathingCue: "Exhale up, inhale down",
        phase: "core", order: 2,
        sets: [
          { id: "d5-llr-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d5-llr-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d5-llr-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30 },
        ],
      },
      {
        id: "d5-bicycle",
        name: "Bicycle Crunch",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Obliques", "Rectus abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Rotating bicycle crunch — elbow to opposite knee while extending the other leg.",
        dos: ["Rotate torso fully", "Keep lower back flat", "Full leg extension each rep"],
        donts: ["Pull neck", "Rush"],
        breathingCue: "Exhale on each rotation",
        phase: "core", order: 3,
        sets: [
          { id: "d5-bc-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-bc-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-bc-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
      {
        id: "d5-heel",
        name: "Heel Touches",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Obliques"],
        musclesSecondary: ["Rectus abdominis"],
        description: "Lying heel-to-heel oblique crunch.",
        dos: ["Shoulders off ground throughout", "Full touch each side"],
        donts: ["Drop back between reps"],
        breathingCue: "Exhale on each touch",
        phase: "core", order: 4,
        sets: [
          { id: "d5-ht-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-ht-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-ht-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
    ],
    elliptical: HIIT_SESSION,
    cooldown: [
      { id: "c5-1", activity: "Walking in place", durationSeconds: 120 },
      { id: "c5-2", activity: "Long hamstring stretch (each leg)", durationSeconds: 30 },
      { id: "c5-3", activity: "Hip flexor stretch (each side)", durationSeconds: 30 },
      { id: "c5-4", activity: "Lower back stretch — knees to chest", durationSeconds: 45 },
      { id: "c5-5", activity: "Savasana", durationSeconds: 180 },
    ],
  },

  /* ──────────── DAY 6 – Barbell Strength Day ──────────── */
  {
    dayNumber: 6,
    name: "Barbell Strength Day",
    focus: "Compound barbell movements — strength & muscle",
    durationMinutes: 55,
    intensity: 5,
    muscleGroups: ["Biceps", "Back", "Legs", "Shoulders", "Core"],
    tags: ["barbell", "compound", "strength", "full-body"],
    warmup: [
      { id: "w6-1", activity: "Nasal breathing — in place", durationSeconds: 90 },
      { id: "w6-2", activity: "Pelvic Tilts", reps: 10 },
      { id: "w6-3", activity: "Bird Dogs", reps: 10, note: "10 per side" },
      { id: "w6-4", activity: "Hip Circles", reps: 10, note: "10 each direction" },
      { id: "w6-5", activity: "Arm Circles", reps: 20, note: "20 forward + 20 back" },
      { id: "w6-6", activity: "Shoulder Rolls", reps: 15 },
      { id: "w6-7", activity: "Bodyweight Squats", reps: 10, note: "Slow, controlled" },
      { id: "w6-8", activity: "Barbell Curl Ramp-Up Set 1 (50%)", reps: 12, note: "Empty rod only" },
      { id: "w6-9", activity: "Barbell Curl Ramp-Up Set 2 (70%)", reps: 8,  note: "1.25 kg per side" },
    ],
    exercises: [
      {
        id: "d6-barbell-curl",
        name: "Barbell Curl",
        category: "biceps",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Biceps brachii (both heads)"],
        musclesSecondary: ["Brachialis", "Brachioradialis"],
        description: "Standing barbell curl — the gold standard for bicep mass. Heavier loading allows stronger progressive overload.",
        dos: ["Elbows pinned to sides", "Full range — complete stretch at bottom", "Controlled 3-second descent", "Brace core for stability"],
        donts: ["Swing torso / use momentum (the #1 mistake)", "Let bar crash down on descent", "Grip too wide or too narrow — shoulder-width"],
        breathingCue: "Exhale curling up, inhale coming down",
        safetyNotes: "If wrists hurt, slightly rotate grip or reduce weight",
        phase: "main",
        order: 1,
        sets: [
          { id: "d6-bc-s1", setNumber: 1, targetWeight: 5.5, targetReps: 10, restSeconds: 90, tempo: "2-0-3-0", notes: "1×1.5kg + 1×1.25kg each side" },
          { id: "d6-bc-s2", setNumber: 2, targetWeight: 5.5, targetReps: 9,  restSeconds: 90 },
          { id: "d6-bc-s3", setNumber: 3, targetWeight: 5.5, targetReps: 8,  restSeconds: 90 },
          { id: "d6-bc-s4", setNumber: 4, targetWeight: 5.5, targetReps: 8,  restSeconds: 90, notes: "Drop 0.5 kg if needed" },
        ],
      },
      {
        id: "d6-bent-row",
        name: "Bent-Over Row",
        category: "back",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Latissimus dorsi", "Rhomboids", "Mid-trapezius"],
        musclesSecondary: ["Biceps brachii", "Rear deltoid", "Erector spinae"],
        description: "Hinge at hips, torso ~45°, pull barbell to lower abdomen. Back rows are critical for posture, opposing the push work and preventing bicep imbalances.",
        dos: ["Hinge from hips — not just bending forward", "Pull elbows BACK, not just up", "Squeeze shoulder blades at the top", "Keep lower back neutral — not rounded"],
        donts: ["Round the lower back", "Let the bar drop uncontrolled", "Use too much leg drive"],
        breathingCue: "Inhale before pull, exhale as you row up",
        phase: "main",
        order: 2,
        sets: [
          { id: "d6-br-s1", setNumber: 1, targetWeight: 7, targetReps: 10, restSeconds: 90, notes: "2kg + 1.5kg each side" },
          { id: "d6-br-s2", setNumber: 2, targetWeight: 7, targetReps: 10, restSeconds: 90 },
          { id: "d6-br-s3", setNumber: 3, targetWeight: 7, targetReps: 10, restSeconds: 90 },
          { id: "d6-br-s4", setNumber: 4, targetWeight: 7, targetReps: 9,  restSeconds: 90 },
        ],
      },
      {
        id: "d6-squat",
        name: "Barbell Back Squat",
        category: "legs",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Quadriceps", "Glutes"],
        musclesSecondary: ["Hamstrings", "Core", "Upper back"],
        description: "Barbell on traps, squat to parallel (or below). The king of compound movements — builds full-body strength.",
        dos: ["Bar on upper traps (not neck)", "Feet shoulder-width, toes slightly out", "Knees track over toes", "Core braced — breath of air before descent"],
        donts: ["Cave knees inward", "Round lower back at the bottom", "Rise on toes"],
        breathingCue: "Big breath in before descent, exhale as you stand",
        safetyNotes: "Use a light weight — technique first. Stop if knees hurt.",
        phase: "main",
        order: 3,
        sets: [
          { id: "d6-sq-s0", setNumber: 0, targetWeight: 0, targetReps: 12, restSeconds: 60, notes: "Empty rod — technique ramp-up" },
          { id: "d6-sq-s1", setNumber: 1, targetWeight: 7, targetReps: 12, restSeconds: 90, notes: "2kg + 1.5kg each side" },
          { id: "d6-sq-s2", setNumber: 2, targetWeight: 7, targetReps: 12, restSeconds: 90 },
          { id: "d6-sq-s3", setNumber: 3, targetWeight: 7, targetReps: 10, restSeconds: 90 },
        ],
      },
      {
        id: "d6-ohp",
        name: "Barbell Overhead Press",
        category: "shoulders",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Anterior deltoid", "Lateral deltoid"],
        musclesSecondary: ["Triceps brachii", "Upper trapezius", "Core"],
        description: "Standing overhead press — grip just outside shoulders, press barbell from upper chest to overhead lockout. Core must stay tight.",
        dos: ["Grip just outside shoulder width", "Press bar in a straight line up", "Full lockout at top", "Brace core hard — glutes squeezed"],
        donts: ["Lean excessively back (arch lower back)", "Flare elbows too wide", "Use leg drive — this is a strict press"],
        breathingCue: "Inhale before press, exhale at lockout",
        phase: "main",
        order: 4,
        sets: [
          { id: "d6-ohp-s1", setNumber: 1, targetWeight: 5.5, targetReps: 10, restSeconds: 90, notes: "Same load as curls" },
          { id: "d6-ohp-s2", setNumber: 2, targetWeight: 5.5, targetReps: 10, restSeconds: 90 },
          { id: "d6-ohp-s3", setNumber: 3, targetWeight: 5.5, targetReps: 8,  restSeconds: 90 },
        ],
      },
      {
        id: "d6-plank-burnout",
        name: "Plank (Core Burnout)",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis"],
        musclesSecondary: ["Glutes", "Shoulders"],
        description: "End of workout core burnout — full plank hold.",
        dos: ["Perfect form only", "Squeeze everything"],
        donts: ["Rush — hold quality over duration"],
        breathingCue: "Steady, controlled breathing",
        phase: "core", order: 5,
        sets: [{ id: "d6-pb-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 30 }],
      },
      {
        id: "d6-mountain-climber",
        name: "Mountain Climbers",
        category: "core", equipment: "bodyweight", difficulty: "intermediate",
        musclesPrimary: ["Core", "Hip flexors"],
        musclesSecondary: ["Shoulders", "Chest"],
        description: "In push-up position, alternate driving knees to chest rapidly.",
        dos: ["Hips level — don't bounce them", "Fast but controlled", "Core tight throughout"],
        donts: ["Let hips rise", "Lose upper body stability"],
        breathingCue: "Breathe rhythmically — don't hold",
        phase: "core", order: 6,
        sets: [{ id: "d6-mc-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 30 }],
      },
      {
        id: "d6-russian-twist",
        name: "Russian Twists",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Obliques", "Transverse abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Sit with torso at 45°, feet slightly raised, rotate side to side touching the floor each time.",
        dos: ["Rotate from the torso — not just arms", "Keep feet raised for more challenge", "Control the movement"],
        donts: ["Round the back", "Use momentum"],
        breathingCue: "Exhale on each twist",
        phase: "core", order: 7,
        sets: [{ id: "d6-rt-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 0, notes: "10 per side" }],
      },
    ],
    cooldown: [
      { id: "c6-1", activity: "Long hamstring stretch (each leg)", durationSeconds: 30 },
      { id: "c6-2", activity: "Hip flexors stretch (each side)", durationSeconds: 30 },
      { id: "c6-3", activity: "Lower back stretch — knees to chest", durationSeconds: 45 },
      { id: "c6-4", activity: "Cat–Cow", reps: 8, note: "Slow and deliberate" },
      { id: "c6-5", activity: "Savasana", durationSeconds: 240, note: "Full recovery rest" },
    ],
  },

  /* ──────────── DAY 7 – Active Recovery ──────────── */
  {
    dayNumber: 7,
    name: "Active Recovery Day",
    focus: "Mobility, flexibility & nervous system reset",
    durationMinutes: 30,
    intensity: 1,
    muscleGroups: ["Full body mobility"],
    tags: ["recovery", "mobility", "flexibility", "rest"],
    warmup: [
      { id: "w7-1", activity: "Slow nasal walk in place", durationSeconds: 120 },
    ],
    exercises: [
      {
        id: "d7-catnow",
        name: "Cat–Cow Flow",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Spinal extensors", "Abdominals"],
        musclesSecondary: ["Hip flexors"],
        description: "On hands and knees — arch and round the spine slowly in rhythm with breath.",
        dos: ["Move with the breath — not against it", "Full range each direction", "Look up on cow, tuck chin on cat"],
        donts: ["Rush", "Hold breath"],
        breathingCue: "Inhale cow (arch), exhale cat (round)",
        phase: "warmup", order: 1,
        sets: [{ id: "d7-cc-s1", setNumber: 1, targetWeight: null, targetReps: 10, restSeconds: 0 }],
      },
      {
        id: "d7-child-pose",
        name: "Child's Pose",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Lats", "Thoracic spine"],
        musclesSecondary: ["Hip flexors", "Glutes"],
        description: "Kneel and sit back on heels, arms stretched forward. Breathe into the lower back.",
        dos: ["Reach arms long", "Breathe into your lower back — feel it expand", "Relax completely"],
        donts: ["Force the position"],
        breathingCue: "Long 4-count inhale, 6-count exhale",
        phase: "cooldown", order: 2,
        sets: [{ id: "d7-cp-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 0 }],
      },
      {
        id: "d7-hip-flexor",
        name: "Kneeling Hip Flexor Stretch",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Iliopsoas", "Rectus femoris"],
        musclesSecondary: ["Glutes"],
        description: "Kneel on one knee, other foot forward. Shift hips forward gently. Hold and breathe.",
        dos: ["Keep upright torso", "Tuck posterior pelvis slightly", "Hold 30 sec per side"],
        donts: ["Lean forward aggressively"],
        breathingCue: "Breathe into the stretch — exhale deeper into it",
        phase: "cooldown", order: 3,
        sets: [{ id: "d7-hf-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 0, notes: "Each side" }],
      },
      {
        id: "d7-thread",
        name: "Thread-the-Needle",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Thoracic rotators", "Rhomboids"],
        musclesSecondary: ["Shoulder external rotators"],
        description: "On hands and knees, slide one arm under your body rotating the thoracic spine. Chest toward the floor.",
        dos: ["Keep hips stacked over knees", "Rotate from the mid-back", "Breathe into the stretch"],
        donts: ["Rotate from the lower back"],
        breathingCue: "Exhale to rotate deeper",
        phase: "cooldown", order: 4,
        sets: [{ id: "d7-tn-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 0, notes: "Each side" }],
      },
      {
        id: "d7-savasana",
        name: "Savasana (Full Body Rest)",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Central nervous system reset"],
        musclesSecondary: [],
        description: "Lie flat on your back, arms at sides, eyes closed. Complete stillness. This is active recovery for your nervous system.",
        dos: ["Eyes closed", "Let your body feel heavy into the floor", "Focus only on your breath"],
        donts: ["Check phone", "Rush out of it"],
        breathingCue: "Natural breath — observe, don't control",
        phase: "cooldown", order: 5,
        sets: [{ id: "d7-sav-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 300, restSeconds: 0 }],
      },
    ],
    cooldown: [],
  },
];

export const WEIGHT_COMBINATIONS = [
  { label: "Rod only", kg: 0, perSide: 0 },
  { label: "1.25 kg per side", kg: 2.5, perSide: 1.25 },
  { label: "1.5 kg per side",  kg: 3.0, perSide: 1.5 },
  { label: "2 kg per side",    kg: 4.0, perSide: 2.0 },
  { label: "1.25+1.25 per side", kg: 5.0, perSide: 2.5 },
  { label: "1.5+1.25 per side",  kg: 5.5, perSide: 2.75 },
  { label: "1.5+1.5 per side",   kg: 6.0, perSide: 3.0 },
  { label: "2+1.25 per side",    kg: 6.5, perSide: 3.25 },
  { label: "2+1.5 per side",     kg: 7.0, perSide: 3.5 },
  { label: "2+2 per side",       kg: 8.0, perSide: 4.0 },
];
