import type { WorkoutDay, EllipticalSession } from "./types";

/* ─── Reusable Elliptical Sessions ─── */

export const HIIT_SESSION: EllipticalSession = {
  id: "elliptical-hiit",
  name: "Elliptical HIIT",
  totalMinutes: 27,
  estimatedCalories: 280,
  intervals: [
    { id: "e1", label: "Easy Warm-up", resistance: 3, durationSeconds: 120, pace: "easy", note: "Settle into rhythm, breathe through nose" },
    { id: "e2", label: "Warm-up Build", resistance: 4, durationSeconds: 120, pace: "easy", note: "Slightly increase cadence" },
    { id: "e3", label: "Warm-up Push", resistance: 5, durationSeconds: 60,  pace: "moderate", note: "Getting the heart rate up" },
    { id: "e4", label: "Sprint Round 1", resistance: 10, durationSeconds: 60, pace: "sprint", note: "Push hard — drive with legs AND arms" },
    { id: "e5", label: "Recovery 1",    resistance: 4,  durationSeconds: 120, pace: "recovery", note: "Active recovery, keep moving" },
    { id: "e6", label: "Sprint Round 2", resistance: 10, durationSeconds: 60, pace: "sprint" },
    { id: "e7", label: "Recovery 2",    resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e8", label: "Sprint Round 3", resistance: 11, durationSeconds: 60, pace: "sprint", note: "Increase resistance this round" },
    { id: "e9", label: "Recovery 3",    resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e10", label: "Sprint Round 4", resistance: 11, durationSeconds: 60, pace: "sprint" },
    { id: "e11", label: "Recovery 4",   resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e12", label: "Sprint Round 5", resistance: 11, durationSeconds: 60, pace: "sprint", note: "Dig deep — last hard rounds!" },
    { id: "e13", label: "Recovery 5",   resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e14", label: "Sprint Round 6", resistance: 10, durationSeconds: 60, pace: "sprint" },
    { id: "e15", label: "Recovery 6",   resistance: 4,  durationSeconds: 120, pace: "recovery" },
    { id: "e16", label: "Cool Down",    resistance: 2,  durationSeconds: 300, pace: "cooldown", note: "Gradual slow-down, deep breathing" },
  ],
};

export const FAT_BURN_SESSION: EllipticalSession = {
  id: "elliptical-fat-burn",
  name: "Fat Burn Steady State",
  totalMinutes: 35,
  estimatedCalories: 320,
  intervals: [
    { id: "f1", label: "Warm-up",    resistance: 3, durationSeconds: 300, pace: "easy",     note: "Build into zone 2 — conversational pace" },
    { id: "f2", label: "Fat Burn Zone", resistance: 5, durationSeconds: 1500, pace: "moderate", note: "You can talk in sentences but can't sing. Resistance 5–6" },
    { id: "f3", label: "Cool Down",  resistance: 2, durationSeconds: 300, pace: "cooldown", note: "Let heart rate come down naturally" },
  ],
};

/* ─── 6-Week Program ─── */

export const WORKOUT_PROGRAM: WorkoutDay[] = [
  /* ──────────── DAY 1 – Cardio HIIT + Abs ──────────── */
  {
    dayNumber: 1,
    name: "Cardio HIIT + Abs",
    focus: "Cardiovascular conditioning & core",
    durationMinutes: 45,
    intensity: 4,
    muscleGroups: ["Core", "Full body cardio"],
    tags: ["hiit", "cardio", "abs", "fat-burn"],
    warmup: [
      { id: "w1-1", activity: "Cat–Cow", reps: 8, note: "Slow and controlled — mobilize the spine" },
      { id: "w1-2", activity: "Slow Bodyweight Squats", reps: 10, note: "Feet shoulder-width apart, go to depth. Knees tracking over toes" },
      { id: "w1-3", activity: "Arm Circles", reps: 10, note: "10 forward, 10 backward — warm shoulder joint" },
      { id: "w1-4", activity: "Ankle Circles", reps: 10, note: "10 each direction, each foot — loosens ankle which protects the knee" },
      { id: "w1-5", activity: "Standing Calf Raises (slow)", reps: 15, note: "Hold top 1 sec. Builds the ankle-calf complex that absorbs knee stress on the elliptical" },
    ],
    exercises: [
      {
        id: "d1-plank",
        name: "Plank",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis", "Rectus abdominis"],
        musclesSecondary: ["Glutes", "Shoulders"],
        description: "Hold a straight-body position supported on forearms and toes. Think of creating a stiff plank from head to heel.",
        dos: ["Keep hips level — not sagging or piked", "Drive elbows into floor", "Breathe steadily throughout", "Squeeze glutes"],
        donts: ["Let hips drop or rise", "Hold your breath", "Crane your neck forward"],
        breathingCue: "Inhale through nose, slow exhale through mouth — brace on exhale",
        safetyNotes: "If lower back hurts, drop to knees and build up",
        phase: "core",
        order: 1,
        sets: [
          { id: "d1-plank-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 45, restSeconds: 30 },
          { id: "d1-plank-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 50, restSeconds: 30 },
          { id: "d1-plank-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 30 },
        ],
      },
      {
        id: "d1-llr",
        name: "Lying Leg Raises",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Lower rectus abdominis", "Hip flexors"],
        musclesSecondary: ["Transverse abdominis"],
        description: "Lie flat on your back, legs together. Raise legs to 90° keeping them straight, then lower slowly without touching floor.",
        dos: ["Press lower back into the mat", "Control the descent — 3 seconds down", "Exhale as legs rise"],
        donts: ["Let lower back arch off the floor", "Swing legs with momentum", "Let feet touch the ground between reps"],
        breathingCue: "Exhale as legs go up, inhale as they come down",
        phase: "core",
        order: 2,
        sets: [
          { id: "d1-llr-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d1-llr-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d1-llr-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30 },
        ],
      },
      {
        id: "d1-bicycle",
        name: "Bicycle Crunch",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Obliques", "Rectus abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Lie on back, hands behind head. Alternate bringing elbow to opposite knee in a cycling motion. Slow and deliberate.",
        dos: ["Rotate torso — not just elbows", "Keep lower back pressed down", "Full extension of opposite leg each rep"],
        donts: ["Pull on your neck", "Rush the movement", "Let shoulders hunch"],
        breathingCue: "Exhale forcefully on each rotation",
        phase: "core",
        order: 3,
        sets: [
          { id: "d1-bicycle-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-bicycle-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-bicycle-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
      {
        id: "d1-heel",
        name: "Heel Touches",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Obliques"],
        musclesSecondary: ["Rectus abdominis"],
        description: "Lie on back, knees bent, feet flat. Crunch side-to-side to touch each heel alternately.",
        dos: ["Keep shoulder blades slightly off floor throughout", "Look at the ceiling, not your feet", "Touch each heel fully"],
        donts: ["Relax back to the floor between reps", "Rush — control the movement"],
        breathingCue: "Exhale on each touch",
        phase: "core",
        order: 4,
        sets: [
          { id: "d1-heel-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-heel-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d1-heel-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
    ],
    elliptical: HIIT_SESSION,
    cooldown: [
      { id: "c1-1", activity: "Walking on the spot", durationSeconds: 120, note: "Let heart rate come down" },
      { id: "c1-2", activity: "Standing forward fold", durationSeconds: 30 },
      { id: "c1-3", activity: "Standing hip flexor stretch (each side)", durationSeconds: 30 },
      { id: "c1-4", activity: "Deep breathing", reps: 5, note: "4-count in, 6-count out" },
    ],
  },

  /* ──────────── DAY 2 – Biceps Focus + Upper Body ──────────── */
  {
    dayNumber: 2,
    name: "Biceps Focus + Upper Body",
    focus: "Biceps hypertrophy, triceps, shoulders",
    durationMinutes: 50,
    intensity: 4,
    muscleGroups: ["Biceps", "Triceps", "Shoulders"],
    tags: ["biceps", "upper-body", "hypertrophy"],
    warmup: [
      { id: "w2-1", activity: "Light Elliptical", durationSeconds: 150, note: "Resistance 3 — just elevate heart rate" },
      { id: "w2-2", activity: "Arm Circles", reps: 20, note: "20 forward + 20 backward" },
      { id: "w2-3", activity: "Shoulder Rolls", reps: 15 },
      { id: "w2-4", activity: "Wrist Circles", reps: 20, note: "20 each direction" },
      { id: "w2-5", activity: "Elbow Flex–Extend", reps: 15, note: "No weight — prime the elbow joint" },
      { id: "w2-6", activity: "Light DB Curl (ramp-up set 1)", reps: 15, note: "Rod only — zero plates. Prime the movement pattern." },
      { id: "w2-7", activity: "Ramp-Up Curl Set 2 (~50%)", reps: 12, note: "1.5 kg per side = 3 kg dumbbell. Easy, controlled. Rest 30 sec." },
      { id: "w2-8", activity: "Ramp-Up Curl Set 3 (~70%)", reps: 8,  note: "2 kg per side = 4 kg dumbbell. Challenging but smooth. Rest 45 sec." },
    ],
    exercises: [
      {
        id: "d2-standing-curl",
        name: "Standing Dumbbell Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Biceps brachii (short + long head)"],
        musclesSecondary: ["Brachialis", "Brachioradialis", "Forearm flexors"],
        description: "Stand tall with dumbbells at sides. Curl both dumbbells simultaneously while keeping elbows pinned to your ribcage. Squeeze hard at the top, then lower in 3 seconds.",
        dos: ["Elbows glued to sides throughout", "Full range — complete stretch at bottom", "2 seconds up, 3 seconds down (2-0-3 tempo)", "Supinate wrists at the top (rotate pinky up)"],
        donts: ["Swing body or use momentum", "Allow elbows to drift forward", "Lock wrists awkwardly", "Cut the range of motion short"],
        breathingCue: "Exhale as you curl up, inhale on the way down",
        safetyNotes: "Stop if you feel sharp elbow pain — reduce weight",
        phase: "main",
        order: 1,
        sets: [
          { id: "d2-sc-s1", setNumber: 1, targetWeight: 5.5, targetReps: 10, restSeconds: 75, tempo: "2-0-3-0", notes: "1.5+1.25 kg per side. Step up from 4 kg." },
          { id: "d2-sc-s2", setNumber: 2, targetWeight: 5.5, targetReps: 9,  restSeconds: 75, tempo: "2-0-3-0" },
          { id: "d2-sc-s3", setNumber: 3, targetWeight: 5.5, targetReps: 8,  restSeconds: 90, tempo: "2-0-3-0", notes: "Last set — push to near failure" },
          { id: "d2-sc-s4", setNumber: 4, targetWeight: 5.5, targetReps: 8,  restSeconds: 90, tempo: "2-0-3-0", notes: "Drop to 5 kg if form breaks" },
        ],
      },
      {
        id: "d2-hammer-curl",
        name: "Hammer Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Brachialis", "Brachioradialis"],
        musclesSecondary: ["Biceps brachii"],
        description: "Neutral grip (thumbs up) curl. Builds the brachialis underneath the bicep, making it look thicker and pushes the peak higher.",
        dos: ["Neutral grip throughout — don't rotate", "Elbows stay at sides", "Full extension at the bottom", "Controlled 3-second descent"],
        donts: ["Supinate — keep thumbs up the whole time", "Use heavy weight at the expense of form", "Rush the eccentric"],
        breathingCue: "Exhale curling up, inhale coming down",
        phase: "main",
        order: 2,
        sets: [
          { id: "d2-hc-s1", setNumber: 1, targetWeight: 4, targetReps: 12, restSeconds: 60, notes: "2 kg per side. Up from 3 kg." },
          { id: "d2-hc-s2", setNumber: 2, targetWeight: 4, targetReps: 10, restSeconds: 60 },
          { id: "d2-hc-s3", setNumber: 3, targetWeight: 4, targetReps: 10, restSeconds: 60 },
        ],
      },
      {
        id: "d2-incline-curl",
        name: "Incline / Seated Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "intermediate",
        musclesPrimary: ["Biceps brachii long head"],
        musclesSecondary: ["Brachialis"],
        description: "Sit on the edge of a chair/couch leaning slightly back. Arms hang behind the body plane — this gives maximum stretch to the long head of the bicep for superior growth.",
        dos: ["Let arms hang freely behind hips", "Curl slowly from full stretch", "Squeeze at top for 1 second", "Keep shoulders back"],
        donts: ["Swing forward to help the lift", "Use too heavy weight — this is a stretch movement", "Round shoulders forward"],
        breathingCue: "Long exhale as you curl, slow inhale on descent",
        phase: "main",
        order: 3,
        sets: [
          { id: "d2-ic-s1", setNumber: 1, targetWeight: 4, targetReps: 12, restSeconds: 60, notes: "2 kg per side. This is a stretch-focused move — keep controlled even at higher weight." },
          { id: "d2-ic-s2", setNumber: 2, targetWeight: 4, targetReps: 10, restSeconds: 60 },
          { id: "d2-ic-s3", setNumber: 3, targetWeight: 4, targetReps: 10, restSeconds: 60 },
        ],
      },
      {
        id: "d2-tricep-ext",
        name: "Overhead DB Triceps Extension",
        category: "triceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Triceps brachii (long head)"],
        musclesSecondary: ["Anconeus"],
        description: "Hold one dumbbell overhead with both hands. Lower it behind your head by bending elbows, keeping upper arms vertical. Extend back up.",
        dos: ["Keep upper arms vertical and still", "Full range of motion — get a deep stretch at the bottom", "Elbows close together", "Very light weight — this is an isolation move"],
        donts: ["Flare elbows wide", "Use heavy weight", "Let upper arms drift forward"],
        breathingCue: "Inhale going down (stretch), exhale driving up",
        phase: "main",
        order: 4,
        sets: [
          { id: "d2-te-s1", setNumber: 1, targetWeight: 4, targetReps: 15, restSeconds: 45, notes: "Both hands on one dumbbell. Up from 3 kg." },
          { id: "d2-te-s2", setNumber: 2, targetWeight: 4, targetReps: 12, restSeconds: 45 },
          { id: "d2-te-s3", setNumber: 3, targetWeight: 4, targetReps: 12, restSeconds: 45 },
        ],
      },
      {
        id: "d2-lateral-raise",
        name: "Lateral Raise",
        category: "shoulders",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Lateral deltoid"],
        musclesSecondary: ["Anterior deltoid", "Supraspinatus"],
        description: "Stand with light dumbbells at sides. Raise arms out to the sides to shoulder height with a slight bend in the elbow. 1-second pause at top.",
        dos: ["Keep very light weight (1.25 kg per side)", "Raise to shoulder height only — not above", "Slight forward lean improves lateral delt engagement", "1-second squeeze at the top"],
        donts: ["Use momentum or shrug", "Go above shoulder height", "Lock elbows straight"],
        breathingCue: "Exhale as arms rise, inhale on way down",
        phase: "main",
        order: 5,
        sets: [
          { id: "d2-lr-s1", setNumber: 1, targetWeight: 3, targetReps: 15, restSeconds: 45, notes: "1.5 kg per side. Lateral delts are easily injured — step up slowly." },
          { id: "d2-lr-s2", setNumber: 2, targetWeight: 3, targetReps: 12, restSeconds: 45 },
          { id: "d2-lr-s3", setNumber: 3, targetWeight: 3, targetReps: 12, restSeconds: 45 },
        ],
      },
    ],
    cooldown: [
      { id: "c2-1", activity: "Bicep wall stretch (each arm)", durationSeconds: 30 },
      { id: "c2-2", activity: "Overhead triceps stretch (each arm)", durationSeconds: 30 },
      { id: "c2-3", activity: "Shoulder cross-body stretch (each arm)", durationSeconds: 30 },
      { id: "c2-4", activity: "Wrist flexor & extensor stretch", durationSeconds: 30 },
    ],
  },

  /* ──────────── DAY 3 – Fat Burn Elliptical + Core ──────────── */
  {
    dayNumber: 3,
    name: "Fat Burn Cardio + Core",
    focus: "Aerobic fat burn & core strengthening",
    durationMinutes: 50,
    intensity: 3,
    muscleGroups: ["Core", "Cardiovascular system"],
    tags: ["cardio", "fat-burn", "core", "steady-state"],
    warmup: [
      { id: "w3-1", activity: "Nasal breathing walk in place", durationSeconds: 90 },
      { id: "w3-2", activity: "Hip circles", reps: 10, note: "10 each direction" },
      { id: "w3-3", activity: "Arm circles", reps: 20, note: "20 forward + 20 backward" },
      { id: "w3-4", activity: "Shoulder rolls", reps: 15 },
    ],
    exercises: [
      {
        id: "d3-side-plank",
        name: "Side Plank",
        category: "core",
        equipment: "bodyweight",
        difficulty: "intermediate",
        musclesPrimary: ["Obliques (internal + external)", "Quadratus lumborum"],
        musclesSecondary: ["Glutes", "Shoulder stabilisers"],
        description: "Lie on side, prop up on forearm with elbow under shoulder. Lift hips to create a straight line from head to feet. Hold.",
        dos: ["Stack feet or stagger for easier balance", "Keep hips stacked — don't rotate forward", "Push forearm into floor actively", "Look forward"],
        donts: ["Let hips sag", "Rotate your top hip back", "Forget to do both sides"],
        breathingCue: "Steady breathing — in through nose, out through mouth",
        phase: "core",
        order: 1,
        sets: [
          { id: "d3-sp-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 35, notes: "Both sides = 1 set" },
          { id: "d3-sp-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 35, restSeconds: 35 },
          { id: "d3-sp-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 40, restSeconds: 35 },
        ],
      },
      {
        id: "d3-dead-bug",
        name: "Dead Bug",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis", "Rectus abdominis"],
        musclesSecondary: ["Hip flexors", "Shoulder stabilisers"],
        description: "Lie on back, arms straight up over shoulders, knees bent at 90° over hips. Slowly lower opposite arm + leg toward floor while pressing lower back down, then return.",
        dos: ["Press lower back firmly into the mat throughout", "Move arm and leg simultaneously", "Exhale FULLY on each rep", "Move slowly — 3 seconds each way"],
        donts: ["Let lower back arch off the floor", "Rush the movement", "Hold your breath"],
        breathingCue: "Exhale as limbs extend, inhale as they return",
        phase: "core",
        order: 2,
        sets: [
          { id: "d3-db-s1", setNumber: 1, targetWeight: null, targetReps: 10, restSeconds: 30, notes: "10 per side = 1 set" },
          { id: "d3-db-s2", setNumber: 2, targetWeight: null, targetReps: 10, restSeconds: 30 },
          { id: "d3-db-s3", setNumber: 3, targetWeight: null, targetReps: 10, restSeconds: 30 },
        ],
      },
      {
        id: "d3-reverse-crunch",
        name: "Reverse Crunch",
        category: "core",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Lower rectus abdominis"],
        musclesSecondary: ["Transverse abdominis", "Hip flexors"],
        description: "Lie on back, knees bent at 90°. Curl the pelvis upward — bringing knees toward chest by contracting the lower abs, not swinging. Lower with control.",
        dos: ["Focus on curling the pelvis — small controlled movement", "Exhale hard at the top", "Control the eccentric (3 second lower)", "Hands flat by sides for stability"],
        donts: ["Swing legs — that's hip flexors, not abs", "Let lower back slam down", "Use momentum"],
        breathingCue: "Exhale forcefully as pelvis curls up",
        phase: "core",
        order: 3,
        sets: [
          { id: "d3-rc-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d3-rc-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d3-rc-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30 },
        ],
      },
    ],
    elliptical: FAT_BURN_SESSION,
    cooldown: [
      { id: "c3-1", activity: "Thread-the-needle stretch (each side)", durationSeconds: 30 },
      { id: "c3-2", activity: "Child's pose", durationSeconds: 45 },
      { id: "c3-3", activity: "Hip flexor stretch (each side)", durationSeconds: 30 },
      { id: "c3-4", activity: "Savasana — deep rest", durationSeconds: 180, note: "Eyes closed, full-body relaxation" },
    ],
  },

  /* ──────────── DAY 4 – Biceps Volume + Chest Push ──────────── */
  {
    dayNumber: 4,
    name: "Biceps Volume + Chest",
    focus: "Biceps volume accumulation & chest/triceps",
    durationMinutes: 50,
    intensity: 4,
    muscleGroups: ["Biceps", "Chest", "Triceps"],
    tags: ["biceps", "chest", "push", "volume"],
    warmup: [
      { id: "w4-1", activity: "Light Elliptical / Brisk Walk", durationSeconds: 150, note: "Resistance 3–4 — just raise body temperature" },
      { id: "w4-2", activity: "Arm Circles (small → big)", reps: 20, note: "20 forward + 20 backward" },
      { id: "w4-3", activity: "Shoulder Rolls", reps: 15 },
      { id: "w4-4", activity: "Wrist Circles", reps: 20, note: "20 each direction" },
      { id: "w4-5", activity: "Elbow Flex–Extend", reps: 15, note: "No weight" },
      { id: "w4-6", activity: "Light DB Curl (rod only)", reps: 15 },
      { id: "w4-7", activity: "Ramp-Up — Alternating DB Curl 50%", reps: 12 },
      { id: "w4-8", activity: "Ramp-Up — Alternating DB Curl 70%", reps: 8 },
    ],
    exercises: [
      {
        id: "d4-alt-curl",
        name: "Alternating Dumbbell Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Biceps brachii"],
        musclesSecondary: ["Brachialis", "Forearm flexors"],
        description: "Curl one arm at a time while the other stays lowered. Allows slightly more focus on each arm and greater volume accumulation.",
        dos: ["Fully lower one arm before starting the other", "Supinate on the way up", "Elbows stay at sides", "Same tempo — 2 up, 3 down"],
        donts: ["Rush — treat each arm independently", "Lean to help one side", "Forget the eccentric on each rep"],
        breathingCue: "Exhale with each curl, inhale on descent",
        phase: "main",
        order: 1,
        sets: [
          { id: "d4-ac-s1", setNumber: 1, targetWeight: 5.5, targetReps: 12, restSeconds: 75, tempo: "2-0-3-0", notes: "1.5+1.25 kg per side" },
          { id: "d4-ac-s2", setNumber: 2, targetWeight: 5.5, targetReps: 12, restSeconds: 75 },
          { id: "d4-ac-s3", setNumber: 3, targetWeight: 5.5, targetReps: 10, restSeconds: 75 },
          { id: "d4-ac-s4", setNumber: 4, targetWeight: 5.5, targetReps: 10, restSeconds: 90, notes: "Drop to 5 kg if form breaks" },
        ],
      },
      {
        id: "d4-concentration-curl",
        name: "Concentration Curl",
        category: "biceps",
        equipment: "dumbbell",
        difficulty: "beginner",
        musclesPrimary: ["Biceps brachii (peak)"],
        musclesSecondary: ["Brachialis"],
        description: "Sit with legs apart, rest elbow on inner thigh. Curl with full focus on that arm. This isolates the bicep peak.",
        dos: ["Rest elbow on INNER thigh — not the top of thigh", "Full range — complete stretch at bottom", "Rotate wrist outward (pinky up) at the top", "Go slow on the way down"],
        donts: ["Rest elbow mid-thigh (too unstable)", "Swing upper arm", "Use too much weight"],
        breathingCue: "Exhale curling, inhale descending",
        phase: "main",
        order: 2,
        sets: [
          { id: "d4-cc-s1", setNumber: 1, targetWeight: 4, targetReps: 12, restSeconds: 60, notes: "Each arm. 2 kg per side. Isolation — keep pristine form." },
          { id: "d4-cc-s2", setNumber: 2, targetWeight: 4, targetReps: 12, restSeconds: 60 },
          { id: "d4-cc-s3", setNumber: 3, targetWeight: 4, targetReps: 10, restSeconds: 60 },
        ],
      },
      {
        id: "d4-pushup",
        name: "Push-ups",
        category: "chest",
        equipment: "pushup_bracket",
        difficulty: "beginner",
        musclesPrimary: ["Pectoralis major", "Anterior deltoid"],
        musclesSecondary: ["Triceps brachii", "Serratus anterior"],
        description: "Use push-up brackets for deeper range of motion. Hands shoulder-width apart, lower chest to bracket level (lower than floor!), press back up.",
        dos: ["Use brackets to get extra depth (incredible chest stretch)", "Keep body rigid — squeeze core and glutes", "Lower in 2 seconds, press in 1 second", "Elbows at 45° angle to torso"],
        donts: ["Sag hips or pike them up", "Let elbows flare to 90°", "Rush the descent"],
        breathingCue: "Inhale going down, exhale pressing up",
        phase: "main",
        order: 3,
        sets: [
          { id: "d4-pu-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 60 },
          { id: "d4-pu-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 60 },
          { id: "d4-pu-s3", setNumber: 3, targetWeight: null, targetReps: 12, restSeconds: 60 },
          { id: "d4-pu-s4", setNumber: 4, targetWeight: null, targetReps: 12, restSeconds: 60 },
        ],
      },
      {
        id: "d4-diamond-pushup",
        name: "Diamond Push-ups",
        category: "triceps",
        equipment: "pushup_bracket",
        difficulty: "intermediate",
        musclesPrimary: ["Triceps brachii (all 3 heads)"],
        musclesSecondary: ["Inner chest", "Anterior deltoid"],
        description: "Form a diamond shape with index fingers and thumbs. Lower chest to hands, press back up. Intense triceps isolation.",
        dos: ["Keep diamond shape tight at centre of chest", "Full ROM — chest touches hands at bottom", "Elbows stay close to body", "Take extra rest — these are hard"],
        donts: ["Flare elbows out", "Partial reps — go all the way down", "Rush if fatigued"],
        breathingCue: "Inhale down, exhale up",
        phase: "main",
        order: 4,
        sets: [
          { id: "d4-dp-s1", setNumber: 1, targetWeight: null, targetReps: 10, restSeconds: 75 },
          { id: "d4-dp-s2", setNumber: 2, targetWeight: null, targetReps: 8,  restSeconds: 75 },
          { id: "d4-dp-s3", setNumber: 3, targetWeight: null, targetReps: 8,  restSeconds: 75 },
        ],
      },
    ],
    cooldown: [
      { id: "c4-1", activity: "Chest doorway stretch", durationSeconds: 30 },
      { id: "c4-2", activity: "Bicep wall stretch (each arm)", durationSeconds: 30 },
      { id: "c4-3", activity: "Triceps overhead stretch (each arm)", durationSeconds: 30 },
      { id: "c4-4", activity: "Cat–Cow", reps: 8 },
    ],
  },

  /* ──────────── DAY 5 – HIIT + Abs ──────────── */
  {
    dayNumber: 5,
    name: "HIIT Cardio + Abs",
    focus: "High-intensity interval training & core burn",
    durationMinutes: 45,
    intensity: 5,
    muscleGroups: ["Core", "Full body cardio"],
    tags: ["hiit", "cardio", "abs", "high-intensity"],
    warmup: [
      { id: "w5-1", activity: "Easy Elliptical", durationSeconds: 120, note: "Resistance 3 — just loosen up" },
      { id: "w5-2", activity: "Marching Knee Raises", durationSeconds: 60 },
      { id: "w5-3", activity: "Arm circles", reps: 20 },
      { id: "w5-4", activity: "Ankle Circles", reps: 10, note: "10 each direction, each foot" },
      { id: "w5-5", activity: "Standing Calf Raises (slow)", reps: 15, note: "Hold top 1 sec. Warms the calf-ankle complex before HIIT" },
      { id: "w5-6", activity: "Slow Knee Bends (wall support)", reps: 10, note: "Stand near wall, bend each knee slowly to 90° and hold 2 sec. Activate VMO before sprints." },
    ],
    exercises: [
      {
        id: "d5-plank",
        name: "Plank",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis", "Rectus abdominis"],
        musclesSecondary: ["Glutes", "Shoulders"],
        description: "Hold a straight-body position on forearms and toes. Core braced like you're about to take a punch.",
        dos: ["Neutral spine", "Drive elbows into floor", "Squeeze glutes hard"],
        donts: ["Let hips sag or rise", "Hold breath"],
        breathingCue: "Slow steady breaths — don't hold",
        phase: "core", order: 1,
        sets: [
          { id: "d5-pl-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 50, restSeconds: 30 },
          { id: "d5-pl-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 55, restSeconds: 30 },
          { id: "d5-pl-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 30 },
        ],
      },
      {
        id: "d5-llr",
        name: "Lying Leg Raises",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Lower rectus abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Lie flat, raise legs to 90°, lower in 3 seconds without touching the floor.",
        dos: ["Lower back pressed down", "3-second descent", "No floor touch between reps"],
        donts: ["Arch lower back", "Use momentum"],
        breathingCue: "Exhale up, inhale down",
        phase: "core", order: 2,
        sets: [
          { id: "d5-llr-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d5-llr-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d5-llr-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30 },
        ],
      },
      {
        id: "d5-bicycle",
        name: "Bicycle Crunch",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Obliques", "Rectus abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Rotating bicycle crunch — elbow to opposite knee while extending the other leg.",
        dos: ["Rotate torso fully", "Keep lower back flat", "Full leg extension each rep"],
        donts: ["Pull neck", "Rush"],
        breathingCue: "Exhale on each rotation",
        phase: "core", order: 3,
        sets: [
          { id: "d5-bc-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-bc-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-bc-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
      {
        id: "d5-heel",
        name: "Heel Touches",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Obliques"],
        musclesSecondary: ["Rectus abdominis"],
        description: "Lying heel-to-heel oblique crunch.",
        dos: ["Shoulders off ground throughout", "Full touch each side"],
        donts: ["Drop back between reps"],
        breathingCue: "Exhale on each touch",
        phase: "core", order: 4,
        sets: [
          { id: "d5-ht-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-ht-s2", setNumber: 2, targetWeight: null, targetReps: 20, restSeconds: 30 },
          { id: "d5-ht-s3", setNumber: 3, targetWeight: null, targetReps: 20, restSeconds: 30 },
        ],
      },
    ],
    elliptical: HIIT_SESSION,
    cooldown: [
      { id: "c5-1", activity: "Walking in place", durationSeconds: 120 },
      { id: "c5-2", activity: "Long hamstring stretch (each leg)", durationSeconds: 30 },
      { id: "c5-3", activity: "Hip flexor stretch (each side)", durationSeconds: 30 },
      { id: "c5-4", activity: "Lower back stretch — knees to chest", durationSeconds: 45 },
      { id: "c5-5", activity: "Savasana", durationSeconds: 180 },
    ],
  },

  /* ──────────── DAY 6 – Barbell Strength Day ──────────── */
  {
    dayNumber: 6,
    name: "Barbell Strength Day",
    focus: "Compound barbell movements — strength & muscle",
    durationMinutes: 55,
    intensity: 5,
    muscleGroups: ["Biceps", "Back", "Legs", "Shoulders", "Core"],
    tags: ["barbell", "compound", "strength", "full-body"],
    warmup: [
      { id: "w6-1", activity: "Nasal breathing — in place", durationSeconds: 90 },
      { id: "w6-2", activity: "Pelvic Tilts", reps: 10 },
      { id: "w6-3", activity: "Bird Dogs", reps: 10, note: "10 per side" },
      { id: "w6-4", activity: "Hip Circles", reps: 10, note: "10 each direction" },
      { id: "w6-5", activity: "Arm Circles", reps: 20, note: "20 forward + 20 back" },
      { id: "w6-6", activity: "Shoulder Rolls", reps: 15 },
      { id: "w6-7", activity: "Bodyweight Squats", reps: 10, note: "Slow, controlled" },
      { id: "w6-8", activity: "Barbell Curl Ramp-Up Set 1 (~50%)", reps: 12, note: "1.5 kg per side = 3 kg total plates. ~50% of working weight." },
      { id: "w6-9", activity: "Barbell Curl Ramp-Up Set 2 (~70%)", reps: 8,  note: "1.25+1.25 per side = 5 kg total plates. ~70% of working weight." },
    ],
    exercises: [
      {
        id: "d6-barbell-curl",
        name: "Barbell Curl",
        category: "biceps",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Biceps brachii (both heads)"],
        musclesSecondary: ["Brachialis", "Brachioradialis"],
        description: "Standing barbell curl — the gold standard for bicep mass. Heavier loading allows stronger progressive overload.",
        dos: ["Elbows pinned to sides", "Full range — complete stretch at bottom", "Controlled 3-second descent", "Brace core for stability"],
        donts: ["Swing torso / use momentum (the #1 mistake)", "Let bar crash down on descent", "Grip too wide or too narrow — shoulder-width"],
        breathingCue: "Exhale curling up, inhale coming down",
        safetyNotes: "If wrists hurt, slightly rotate grip or reduce weight",
        phase: "main",
        order: 1,
        sets: [
          { id: "d6-bc-s1", setNumber: 1, targetWeight: 7, targetReps: 10, restSeconds: 90, tempo: "2-0-3-0", notes: "2 kg + 1.5 kg each side. Up from 5.5 kg." },
          { id: "d6-bc-s2", setNumber: 2, targetWeight: 7, targetReps: 9,  restSeconds: 90 },
          { id: "d6-bc-s3", setNumber: 3, targetWeight: 7, targetReps: 8,  restSeconds: 90 },
          { id: "d6-bc-s4", setNumber: 4, targetWeight: 7, targetReps: 8,  restSeconds: 90, notes: "Drop to 5.5 kg if form breaks" },
        ],
      },
      {
        id: "d6-bent-row",
        name: "Bent-Over Row",
        category: "back",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Latissimus dorsi", "Rhomboids", "Mid-trapezius"],
        musclesSecondary: ["Biceps brachii", "Rear deltoid", "Erector spinae"],
        description: "Hinge at hips, torso ~45°, pull barbell to lower abdomen. Back rows are critical for posture, opposing the push work and preventing bicep imbalances.",
        dos: ["Hinge from hips — not just bending forward", "Pull elbows BACK, not just up", "Squeeze shoulder blades at the top", "Keep lower back neutral — not rounded"],
        donts: ["Round the lower back", "Let the bar drop uncontrolled", "Use too much leg drive"],
        breathingCue: "Inhale before pull, exhale as you row up",
        phase: "main",
        order: 2,
        sets: [
          { id: "d6-br-s1", setNumber: 1, targetWeight: 8, targetReps: 10, restSeconds: 90, notes: "2 kg + 2 kg each side. Up from 7 kg. Back flat, hinge deep." },
          { id: "d6-br-s2", setNumber: 2, targetWeight: 8, targetReps: 10, restSeconds: 90 },
          { id: "d6-br-s3", setNumber: 3, targetWeight: 8, targetReps: 10, restSeconds: 90 },
          { id: "d6-br-s4", setNumber: 4, targetWeight: 8, targetReps: 9,  restSeconds: 90, notes: "Drop to 7 kg if lower back strains" },
        ],
      },
      {
        id: "d6-tke",
        name: "Terminal Knee Extension (TKE)",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["VMO (Vastus Medialis Oblique)", "Quadriceps"],
        musclesSecondary: ["Glutes"],
        description: "Stand with a slight bend in one knee. Slowly straighten the knee fully, squeezing the inner quad (VMO — the teardrop muscle) hard at lockout. Hold 2 sec. This directly strengthens the muscle most responsible for knee stability. Do this BEFORE squatting.",
        dos: ["Feel the inner quad (inner thigh, just above kneecap) fire at lockout", "Slow controlled movement — 2 sec up, 2 sec hold, 2 sec down", "Stay upright — don't lean", "Both legs, one at a time"],
        donts: ["Lock knee aggressively — controlled extension only", "Rush through — the squeeze at lockout is the whole point", "Skip this before squatting — non-negotiable"],
        breathingCue: "Exhale as you extend and squeeze",
        safetyNotes: "No pain — this should feel like a gentle quad activation, nothing sharp",
        phase: "main",
        order: 3,
        sets: [
          { id: "d6-tke-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30, notes: "Each leg. Slow — feel the VMO" },
          { id: "d6-tke-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30, notes: "Each leg" },
        ],
      },
      {
        id: "d6-wall-sit",
        name: "Wall Sit",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Quadriceps", "VMO"],
        musclesSecondary: ["Glutes", "Hamstrings"],
        description: "Back flat against wall, thighs parallel to floor (90° knee angle), hold. Pure isometric quad and VMO strengthening — zero joint stress. Critical for runner's knee prevention.",
        dos: ["90° at the knee — thighs parallel to floor", "Back fully flat against wall", "Feet flat, weight through heels", "Breathe steadily throughout"],
        donts: ["Let knees cave inward", "Push off thighs with hands", "Go past 90° (more is not better here)"],
        breathingCue: "Steady nasal breathing — this is a hold, not a sprint",
        safetyNotes: "If kneecap aches, stop. Mild quad burn is expected — that's the goal.",
        phase: "main",
        order: 4,
        sets: [
          { id: "d6-ws-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 45, notes: "Build to 45 sec over weeks" },
          { id: "d6-ws-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 45 },
        ],
      },
      {
        id: "d6-squat",
        name: "Barbell Back Squat",
        category: "legs",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Quadriceps", "Glutes"],
        musclesSecondary: ["Hamstrings", "Core", "Upper back"],
        description: "Barbell on traps, squat to just below parallel. VMO and TKE work beforehand means your knees are primed. Focus on knee tracking — they must go over your 2nd toe throughout.",
        dos: ["Bar on upper traps (not neck)", "Feet shoulder-width, toes 15–20° out", "Push knees OUT over toes — never let them cave", "Core braced — breath of air before descent", "Sit BACK and DOWN — not just down"],
        donts: ["Cave knees inward on the way up (most common mistake)", "Round lower back at the bottom", "Rise on toes — weight stays through mid-foot"],
        breathingCue: "Big breath in before descent, exhale powerfully as you drive up",
        safetyNotes: "Knees warm from TKE + wall sit. Stop immediately if sharp knee pain — reduce range of motion, not weight.",
        phase: "main",
        order: 5,
        sets: [
          { id: "d6-sq-s0", setNumber: 0, targetWeight: 0, targetReps: 12, restSeconds: 60, notes: "Empty rod — 12 slow reps, feel the knee tracking" },
          { id: "d6-sq-s1", setNumber: 1, targetWeight: 8, targetReps: 12, restSeconds: 90, notes: "2 kg + 2 kg each side. Up from 7 kg." },
          { id: "d6-sq-s2", setNumber: 2, targetWeight: 8, targetReps: 12, restSeconds: 90 },
          { id: "d6-sq-s3", setNumber: 3, targetWeight: 8, targetReps: 10, restSeconds: 90, notes: "Drop to 7 kg if any knee ache" },
        ],
      },
      {
        id: "d6-ohp",
        name: "Barbell Overhead Press",
        category: "shoulders",
        equipment: "barbell",
        difficulty: "intermediate",
        musclesPrimary: ["Anterior deltoid", "Lateral deltoid"],
        musclesSecondary: ["Triceps brachii", "Upper trapezius", "Core"],
        description: "Standing overhead press — grip just outside shoulders, press barbell from upper chest to overhead lockout. Core must stay tight.",
        dos: ["Grip just outside shoulder width", "Press bar in a straight line up", "Full lockout at top", "Brace core hard — glutes squeezed"],
        donts: ["Lean excessively back (arch lower back)", "Flare elbows too wide", "Use leg drive — this is a strict press"],
        breathingCue: "Inhale before press, exhale at lockout",
        phase: "main",
        order: 4,
        sets: [
          { id: "d6-ohp-s1", setNumber: 1, targetWeight: 7, targetReps: 10, restSeconds: 90, notes: "2 kg + 1.5 kg each side. Up from 5.5 kg." },
          { id: "d6-ohp-s2", setNumber: 2, targetWeight: 7, targetReps: 10, restSeconds: 90 },
          { id: "d6-ohp-s3", setNumber: 3, targetWeight: 7, targetReps: 8,  restSeconds: 90, notes: "Drop to 5.5 kg if shoulders fatigue" },
        ],
      },
      {
        id: "d6-plank-burnout",
        name: "Plank (Core Burnout)",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Transverse abdominis"],
        musclesSecondary: ["Glutes", "Shoulders"],
        description: "End of workout core burnout — full plank hold.",
        dos: ["Perfect form only", "Squeeze everything"],
        donts: ["Rush — hold quality over duration"],
        breathingCue: "Steady, controlled breathing",
        phase: "core", order: 5,
        sets: [{ id: "d6-pb-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 30 }],
      },
      {
        id: "d6-mountain-climber",
        name: "Mountain Climbers",
        category: "core", equipment: "bodyweight", difficulty: "intermediate",
        musclesPrimary: ["Core", "Hip flexors"],
        musclesSecondary: ["Shoulders", "Chest"],
        description: "In push-up position, alternate driving knees to chest rapidly.",
        dos: ["Hips level — don't bounce them", "Fast but controlled", "Core tight throughout"],
        donts: ["Let hips rise", "Lose upper body stability"],
        breathingCue: "Breathe rhythmically — don't hold",
        phase: "core", order: 6,
        sets: [{ id: "d6-mc-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 30 }],
      },
      {
        id: "d6-russian-twist",
        name: "Russian Twists",
        category: "core", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Obliques", "Transverse abdominis"],
        musclesSecondary: ["Hip flexors"],
        description: "Sit with torso at 45°, feet slightly raised, rotate side to side touching the floor each time.",
        dos: ["Rotate from the torso — not just arms", "Keep feet raised for more challenge", "Control the movement"],
        donts: ["Round the back", "Use momentum"],
        breathingCue: "Exhale on each twist",
        phase: "core", order: 7,
        sets: [{ id: "d6-rt-s1", setNumber: 1, targetWeight: null, targetReps: 20, restSeconds: 0, notes: "10 per side" }],
      },
    ],
    cooldown: [
      { id: "c6-1", activity: "Standing quad stretch (each leg)", durationSeconds: 30, note: "Hold ankle, knee pointing down. Crucial after squats." },
      { id: "c6-2", activity: "Long hamstring stretch (each leg)", durationSeconds: 30 },
      { id: "c6-3", activity: "Hip flexors stretch (each side)", durationSeconds: 30 },
      { id: "c6-4", activity: "Figure-4 stretch (each side)", durationSeconds: 30, note: "Cross one ankle over the opposite thigh — opens the piriformis and takes pressure off the knee complex" },
      { id: "c6-5", activity: "Lower back stretch — knees to chest", durationSeconds: 45 },
      { id: "c6-6", activity: "Cat–Cow", reps: 8, note: "Slow and deliberate" },
      { id: "c6-7", activity: "Savasana", durationSeconds: 240, note: "Full recovery rest" },
    ],
  },

  /* ──────────── DAY 7 – Knee Prehab + Active Recovery ──────────── */
  {
    dayNumber: 7,
    name: "Knee Prehab + Recovery",
    focus: "Knee strengthening, mobility & nervous system reset",
    durationMinutes: 40,
    intensity: 1,
    muscleGroups: ["Knees", "Hips", "Full body mobility"],
    tags: ["recovery", "mobility", "flexibility", "knee-prehab", "rest"],
    warmup: [
      { id: "w7-1", activity: "Slow nasal walk in place", durationSeconds: 120 },
      { id: "w7-2", activity: "Ankle Circles", reps: 10, note: "10 each direction, each foot" },
      { id: "w7-3", activity: "Knee Circles (standing)", reps: 10, note: "Hands on knees, gently circle both knees together. 10 clockwise + 10 counterclockwise." },
    ],
    exercises: [
      {
        id: "d7-glute-bridge",
        name: "Glute Bridge",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Glutes", "Hamstrings"],
        musclesSecondary: ["Core", "Hip abductors"],
        description: "Lie on back, knees bent, feet flat. Drive hips up by squeezing glutes — hold 2 seconds at top, lower slowly. Strong glutes take load off knees by controlling hip alignment.",
        dos: ["Drive through heels — not toes", "Squeeze glutes hard at the top — 2 sec hold", "Keep knees aligned (not caving in)", "Full hip extension at the top"],
        donts: ["Use lower back to thrust up", "Let knees fall inward", "Rush the descent"],
        breathingCue: "Exhale as hips drive up, inhale coming down",
        safetyNotes: "If lower back aches, you're using it instead of glutes — press heels harder",
        phase: "main",
        order: 1,
        sets: [
          { id: "d7-gb-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d7-gb-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30 },
          { id: "d7-gb-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30, notes: "Try single-leg if this feels easy" },
        ],
      },
      {
        id: "d7-clamshell",
        name: "Clamshell",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Gluteus medius", "Hip abductors"],
        musclesSecondary: ["Gluteus minimus", "Piriformis"],
        description: "Lie on side, hips and knees bent at 45°. Keeping feet together, rotate the top knee upward like a clamshell opening. This trains hip abductors — weak hips = knee valgus (knees caving), which is a primary cause of runner's knee.",
        dos: ["Keep pelvis completely still — don't rock backward", "Open as wide as you can without rotating the pelvis", "Slow controlled movement each rep", "Feel the outer glute working"],
        donts: ["Rock the hips backward to get range", "Rush through the reps", "Let feet separate"],
        breathingCue: "Exhale as knee opens, inhale closing",
        safetyNotes: "No pain — mild outer glute fatigue is the goal",
        phase: "main",
        order: 2,
        sets: [
          { id: "d7-cl-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 20, notes: "Each side" },
          { id: "d7-cl-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 20, notes: "Each side" },
          { id: "d7-cl-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 20, notes: "Each side — feel the outer glute burn" },
        ],
      },
      {
        id: "d7-tke",
        name: "Terminal Knee Extension (TKE)",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["VMO (Vastus Medialis Oblique)"],
        musclesSecondary: ["Quadriceps"],
        description: "Stand near a wall for balance. Slightly bend one knee, then slowly straighten it to full extension while squeezing the inner quad (VMO). The VMO is the teardrop-shaped muscle just above and inside the kneecap — it's THE most important muscle for patellofemoral stability (front knee pain in runners).",
        dos: ["Squeeze the inner quad firmly at full extension — hold 2 sec", "Slow controlled movement — not a kick", "Feel the teardrop muscle above the inner kneecap fire", "Both legs equally"],
        donts: ["Kick or snap the knee straight", "Skip the hold at lockout", "Let knee waver side-to-side"],
        breathingCue: "Exhale as you extend and squeeze",
        safetyNotes: "Should feel like a gentle quad activation. No pain — if sharp pain, stop.",
        phase: "main",
        order: 3,
        sets: [
          { id: "d7-tke-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 20, notes: "Each leg. 2 sec squeeze at top." },
          { id: "d7-tke-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 20, notes: "Each leg" },
          { id: "d7-tke-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 20, notes: "Each leg" },
        ],
      },
      {
        id: "d7-wall-sit",
        name: "Wall Sit",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Quadriceps", "VMO"],
        musclesSecondary: ["Glutes", "Hamstrings"],
        description: "Back flat against wall, thighs parallel to floor. Isometric quad contraction — the safest, most effective exercise for building knee support strength. No impact, no shear force on the joint.",
        dos: ["90° knee angle — thighs parallel to floor", "Back fully flat against wall, no gap", "Feet shoulder-width, flat on floor", "Focus on keeping knees pushed OUT (not caving in)"],
        donts: ["Let knees cave inward", "Push off thighs with hands to cheat", "Slide your back up the wall"],
        breathingCue: "Steady nasal breathing throughout — this is a hold",
        safetyNotes: "Dull quad ache is perfect. Stop if kneecap pain — reduce angle (back higher on wall).",
        phase: "main",
        order: 4,
        sets: [
          { id: "d7-ws-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 45, notes: "Target: 45 sec by week 4, 60 sec by week 8" },
          { id: "d7-ws-s2", setNumber: 2, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 45 },
          { id: "d7-ws-s3", setNumber: 3, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 45, notes: "Push to max duration on last set" },
        ],
      },
      {
        id: "d7-calf-raise",
        name: "Single-Leg Calf Raise",
        category: "legs",
        equipment: "bodyweight",
        difficulty: "beginner",
        musclesPrimary: ["Gastrocnemius", "Soleus"],
        musclesSecondary: ["Ankle stabilisers", "Tibialis anterior"],
        description: "Stand on one foot (near wall for balance), raise heel as high as possible, lower slowly (3 seconds). Calf and ankle strength is strongly correlated with knee health — a stiff or weak ankle transfers force directly to the knee on impact.",
        dos: ["Full range — complete stretch at bottom (heel below step if possible)", "Controlled 3-second descent", "Both sides equally", "Use step or book for extra range if available"],
        donts: ["Bounce at the bottom", "Rush down", "Favour the stronger leg"],
        breathingCue: "Exhale rising, inhale lowering",
        safetyNotes: "If Achilles tight, don't force range — build gradually",
        phase: "main",
        order: 5,
        sets: [
          { id: "d7-cr-s1", setNumber: 1, targetWeight: null, targetReps: 15, restSeconds: 30, notes: "Each leg" },
          { id: "d7-cr-s2", setNumber: 2, targetWeight: null, targetReps: 15, restSeconds: 30, notes: "Each leg" },
          { id: "d7-cr-s3", setNumber: 3, targetWeight: null, targetReps: 15, restSeconds: 30, notes: "Each leg — 3 sec down every rep" },
        ],
      },
      {
        id: "d7-catnow",
        name: "Cat–Cow Flow",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Spinal extensors", "Abdominals"],
        musclesSecondary: ["Hip flexors"],
        description: "On hands and knees — arch and round the spine slowly in rhythm with breath.",
        dos: ["Move with the breath — not against it", "Full range each direction", "Look up on cow, tuck chin on cat"],
        donts: ["Rush", "Hold breath"],
        breathingCue: "Inhale cow (arch), exhale cat (round)",
        phase: "cooldown", order: 6,
        sets: [{ id: "d7-cc-s1", setNumber: 1, targetWeight: null, targetReps: 10, restSeconds: 0 }],
      },
      {
        id: "d7-child-pose",
        name: "Child's Pose",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Lats", "Thoracic spine"],
        musclesSecondary: ["Hip flexors", "Glutes"],
        description: "Kneel and sit back on heels, arms stretched forward. Breathe into the lower back.",
        dos: ["Reach arms long", "Breathe into your lower back — feel it expand", "Relax completely"],
        donts: ["Force the position"],
        breathingCue: "Long 4-count inhale, 6-count exhale",
        phase: "cooldown", order: 7,
        sets: [{ id: "d7-cp-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 60, restSeconds: 0 }],
      },
      {
        id: "d7-hip-flexor",
        name: "Kneeling Hip Flexor Stretch",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Iliopsoas", "Rectus femoris"],
        musclesSecondary: ["Glutes"],
        description: "Kneel on one knee, other foot forward. Shift hips forward gently. Hold and breathe. Tight hip flexors pull the pelvis forward, increasing knee stress when walking/running.",
        dos: ["Keep upright torso", "Tuck posterior pelvis slightly", "Hold 30–45 sec per side"],
        donts: ["Lean forward aggressively"],
        breathingCue: "Breathe into the stretch — exhale deeper into it",
        phase: "cooldown", order: 8,
        sets: [{ id: "d7-hf-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 40, restSeconds: 0, notes: "Each side. 40 sec." }],
      },
      {
        id: "d7-quad-stretch",
        name: "Standing Quad / Rectus Femoris Stretch",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Rectus femoris", "Quadriceps"],
        musclesSecondary: ["Hip flexors"],
        description: "Standing, hold one ankle behind you with knee pointing down. The rectus femoris crosses both the hip and knee — keeping it flexible reduces patellar tendon stress.",
        dos: ["Knee pointing straight down — not flared out", "Stand tall, don't lean forward", "Hold 30–45 sec each side"],
        donts: ["Pull heel to butt (that's a knee stretch, not quad)"],
        breathingCue: "Long slow exhale on each breath to deepen the stretch",
        phase: "cooldown", order: 9,
        sets: [{ id: "d7-qs-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 40, restSeconds: 0, notes: "Each side" }],
      },
      {
        id: "d7-thread",
        name: "Thread-the-Needle",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Thoracic rotators", "Rhomboids"],
        musclesSecondary: ["Shoulder external rotators"],
        description: "On hands and knees, slide one arm under your body rotating the thoracic spine. Chest toward the floor.",
        dos: ["Keep hips stacked over knees", "Rotate from the mid-back", "Breathe into the stretch"],
        donts: ["Rotate from the lower back"],
        breathingCue: "Exhale to rotate deeper",
        phase: "cooldown", order: 10,
        sets: [{ id: "d7-tn-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 30, restSeconds: 0, notes: "Each side" }],
      },
      {
        id: "d7-savasana",
        name: "Savasana (Full Body Rest)",
        category: "mobility", equipment: "bodyweight", difficulty: "beginner",
        musclesPrimary: ["Central nervous system reset"],
        musclesSecondary: [],
        description: "Lie flat on your back, arms at sides, eyes closed. Complete stillness. This is active recovery for your nervous system.",
        dos: ["Eyes closed", "Let your body feel heavy into the floor", "Focus only on your breath"],
        donts: ["Check phone", "Rush out of it"],
        breathingCue: "Natural breath — observe, don't control",
        phase: "cooldown", order: 11,
        sets: [{ id: "d7-sav-s1", setNumber: 1, targetWeight: null, targetReps: null, targetDuration: 300, restSeconds: 0 }],
      },
    ],
    cooldown: [],
  },
];

export const WEIGHT_COMBINATIONS = [
  { label: "Rod only",              kg: 0,    perSide: 0 },
  { label: "1.25 kg per side",      kg: 2.5,  perSide: 1.25 },
  { label: "1.5 kg per side",       kg: 3.0,  perSide: 1.5 },
  { label: "2 kg per side",         kg: 4.0,  perSide: 2.0 },
  { label: "1.25+1.25 per side",    kg: 5.0,  perSide: 2.5 },
  { label: "1.5+1.25 per side",     kg: 5.5,  perSide: 2.75 },
  { label: "1.5+1.5 per side",      kg: 6.0,  perSide: 3.0 },
  { label: "2+1.25 per side",       kg: 6.5,  perSide: 3.25 },
  { label: "2+1.5 per side",        kg: 7.0,  perSide: 3.5 },
  { label: "2+2 per side",          kg: 8.0,  perSide: 4.0 },
  { label: "2+2+1.25 per side",     kg: 10.5, perSide: 5.25 },
  { label: "2+2+1.5 per side",      kg: 11.0, perSide: 5.5 },
  { label: "2+2+2 per side",        kg: 12.0, perSide: 6.0 },
];
